---
- name: Ansible custom facts
  hosts: all
  become: true
  vars:
    factdir: /etc/ansible/facts.d
  tasks:
  - name: Custom fact directory
    file:
      dest: '{{factdir}}'
      state: directory
      owner: root
      group: '{{root_group}}'
      mode: 0755

  - name: Homedir fact
    become: true
    copy:
      dest: '{{factdir}}/homedir.fact'
      content: |
        #!/usr/bin/env python
        from os import environ
        from os.path import expanduser
        user = environ['SUDO_USER'] if 'SUDO_USER' in environ else ''
        print('{"homedir":"%s"}' % expanduser('~%s' % user))
      mode: 0755

- name: Sudo Arch
  hosts: arch
  become: true
  tasks:
    - name: Install sudo
      pacman: name=sudo

- name: Sudo OSX
  hosts: osx
  become: true
  vars_prompt:
    - name: ansible_become_pass
      prompt: 'Ansible sudo password'
      private: yes
  tasks:
    - name: Sudo config dir
      file:
        dest: /etc/sudoers.d
        mode: 0770
        owner: root
        group: '{{root_group}}'
        state: directory

    - name: Sudo includedir
      lineinfile:
        dest: /etc/sudoers
        line: '#includedir /etc/sudoers.d'

- name: Sudo passwordless
  hosts: arch,osx
  become: true
  tasks:
    - name: Passwordless sudo for admin group
      copy:
        content: '%{{wheel_group}} ALL=(ALL) NOPASSWD: ALL'
        dest: /etc/sudoers.d/10_wheel
        mode: 0640
        owner: root
        group: '{{root_group}}'

- name: Create bhaskell user (OS X)
  hosts: 'osx'
  become: true
  vars_prompt:
   - name: user_password
     prompt: initial user password (OS X)
     private: yes
     confirm: yes

  tasks:
    - name: Create user
      user:
        name: bhaskell
        comment: Benjamin R. Haskell
        groups: '{{wheel_group}}'
        shell: /bin/zsh

    - name: Set password
      osxpassword:
        user: bhaskell
        password: '{{user_password}}'

- name: Create bhaskell user
  hosts: '!osx'
  become: true
  vars_prompt:
   - name: user_password
     prompt: initial user password
     private: yes
     confirm: yes
     encrypt: sha512_crypt

  tasks:
    - name: My user
      user: name=bhaskell
        comment='Benjamin R. Haskell'
        groups=wheel
        password={{user_password}}

- name: Per-Host SSH Key
  hosts: all
  vars_prompt:
   - name: ssh_passphrase
     prompt: SSH key passphrase (03)
     private: yes
     confirm: yes

  tasks:
    - name: SSH Key
      sshkey: file=.ssh/id_03_{{ansible_hostname}}
        type=rsa
        bits=4096
        comment=bhaskell@{{ansible_hostname}}
        passphrase={{ssh_passphrase}}

- name: Disable all but key-based SSH
  hosts: osx
  become: true
  tasks:
    - name: Disable password-based auth methods
      lineinfile:
        dest: /etc/sshd_config
        line: '{{item}} no'
        regexp: '^{{item}}'
      with_items:
        - PasswordAuthentication
        - ChallengeResponseAuthentication
