---
- name: Sudo Arch
  hosts: arch
  tasks:
    - name: Install sudo
      pacman: name=sudo

    - name: Passwordless sudo for wheel
      lineinfile: "dest=/etc/sudoers.d/10_wheel
        create=yes
        line='%wheel ALL=(ALL) NOPASSWD: ALL'"

- name: Set up initial user
  hosts: all
  vars_prompt:
   - name: user_password
     prompt: initial user password
     private: yes
     confirm: yes
     encrypt: sha512_crypt

   - name: ssh_passphrase
     prompt: SSH key passphrase (03)
     private: yes
     confirm: yes

  tasks:
    - name: My user
      user: name=bhaskell
        comment='Benjamin R. Haskell'
        groups=wheel
        password={{user_password}}

- name: Per-Host SSH Key
  hosts: all
  vars_prompt:
   - name: ssh_passphrase
     prompt: SSH key passphrase (03)
     private: yes
     confirm: yes

  tasks:
    - name: SSH Key
      sshkey: file=.ssh/id_03_{{ansible_hostname}}
        type=rsa
        bits=4096
        comment=bhaskell@{{ansible_hostname}}
        passphrase={{ssh_passphrase}}
