- name: Android development
  hosts: arch
  vars:
    base: android-studio-ide-135.1740770-linux.zip
    tmp: /tmp/{{base}}
    url: https://dl.google.com/dl/android/studio/ide-zips/1.1.0/{{base}}

  tasks:
    - name: Android Studio
      get_url: url={{url}}
        dest={{tmp}}
        sha256sum=215bc100b1c94354cece28b4b1692ffc3098f386bf76c1ebc05d393f1acd50e4

    - name: Android Studio (install)
      unarchive: copy=no
        src={{tmp}}
        dest=/opt/
        creates=/opt/android-studio

    # TODO: is this needed? Otherwise add a link to the studio-installed tools.
    #
    - name: Android Tools
      sudo: yes
      pacman: name=android-tools

    - name: Android USB debugging
      sudo: yes
      pacman: name=android-udev

    # Work around Aura bug: https://github.com/aurapm/aura/issues/14
    - name: Android SDK deps
      sudo: yes
      pacman: name={{item}}
      with_items:
        - lib32-openal
        - lib32-libstdc++5
        - lib32-libxv
        - lib32-sdl
        - swt

    - name: Android SDK
      sudo: yes
      archpkg: name=aur/android-sdk

    - name: Android USB group (add me)
      sudo: yes
      user: name=bhaskell
        append=yes
        groups=adbusers
