- name: Ansible
  hosts: 'ansible:&arch'
  become: true
  vars:
    state: present

  tasks:
    - name: Python PIP
      pacman: name=python2-pip

    - name: Ansible Modules
      pip: name={{item}} state={{state}} executable=pip2
      with_items:
        - ansible
        - passlib
        - redis
