- name: Aura and ABS
  hosts: arch
  vars:
    binary: '{{homedir}}/.local/bin/aura'
    build: '{{gitbuild}}/aura'

  tasks:
    - name: Arch build system prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - fakeroot

    - name: Arch build system
      become: true
      pacman: name=abs
      notify: set abs perms

    - name: Aura source
      git: repo=gh:aurapm/aura
        dest={{build}}
        update=no
        depth=1

    - name: Aura build package
      shell: stack setup && stack install
        creates={{binary}}
        chdir={{build}}

  handlers:
    - name: set abs perms
      command: set-all-facl -u -R /var/abs
