- name: Aura and ABS
  hosts: arch
  vars:
    binary: '{{homedir}}/.local/bin/aura'
    build: '{{gitbuild}}/aura'

  tasks:
    - name: Arch build system prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - fakeroot

    - name: Arch build system
      become: true
      pacman: name=abs
      notify: set abs perms

    - name: Aura source
      git: repo=gh:aurapm/aura
        dest={{build}}
        update=no
        depth=1

    - name: Aura build package
      shell: |
        if {{binary}} -h >/dev/null 2>/dev/null
        then echo already
        else rm -rf .stack-work && stack setup && stack install
        fi
      args:
        chdir: '{{build}}'
      register: ret
      changed_when: ret.stdout_lines != ["already"]

    - name: Sudo inherit GNUPGHOME
      become: true
      copy:
        content: |
          Cmnd_Alias AURATOOLS = {{binary}},/usr/bin/makepkg
          Defaults!AURATOOLS env_keep+=GNUPGHOME
        dest: /etc/sudoers.d/20_aura
        owner: root
        group: root
        mode: 0644

  handlers:
    - name: set abs perms
      command: set-all-facl -u -R /var/abs
