- name: Aura and ABS
  hosts: arch
  vars:
    archbuilds: /opt/arch-builds
    tarball: '{{archbuilds}}/aura.tar.gz'
    pkg: '{{archbuilds}}/aura/aura-1.3.0.5-1-x86_64.pkg.tar.xz'

  tasks:
    - name: Arch build system prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - fakeroot

    - name: Arch build system
      sudo: yes
      pacman: name=abs
      notify: set abs perms

    - name: AUR build dir
      file: path={{archbuilds}} state=directory owner=bhaskell group=bhaskell

    - name: Aura prereqs
      shell: ghc-pkg list --simple {{item}} | grep -q . ||
        cabal install {{item}}
      with_items:
        - regex-base
        - parsec
        - syb
        - mtl
        - json
        - temporary
        - regex-pcre-builtin
        - http-conduit
        - lens
        - split
        - wreq
        - aur
      register: cabal
      changed_when: cabal.stdout != ''

    - name: Aura source
      get_url: url=https://aur.archlinux.org/packages/au/aura/aura.tar.gz
        dest={{tarball}}

    - name: Aura build package
      shell: cd {{archbuilds}} &&
        tar xvf {{tarball}} &&
        cd aura &&
        perl -000 -i -lpwe 's/^(makedepends=\().*?\)/$1)/sm' PKGBUILD &&
        makepkg -si
        creates={{pkg}}
        chdir={{archbuilds}}

    - name: Aura install
      sudo: yes
      command: pacman --noconfirm -U {{pkg}}
        creates=/usr/sbin/aura

  handlers:
    - name: set abs perms
      command: set-all-facl -u -R /var/abs
