- name: Arch packaging
  hosts: arch
  become: true
  vars:
    mirrorlist: /etc/pacman.d/mirrorlist
    repos: [core, extra, community, multilib]
    deprecated: [atlassian, testing]

  tasks:
    - name: Ensure old repos are deleted
      file:
        name: '/etc/pacman.d/repo.{{item}}'
        state: absent
      with_items: '{{deprecated}}'

    - name: Disable all repos (no includes)
      lineinfile: dest=/etc/pacman.conf
        state=absent
        regexp='^Include\s*=\s*/etc/pacman\.d/repo'
      notify: Update packages

    - name: Disable all repos (no sections)
      replace: dest=/etc/pacman.conf
        regexp='^\[(?!options\]$)(.+)\]$'
        replace='#[\1]'
      notify: Update packages

    - name: Add include for chosen repos
      lineinfile: dest=/etc/pacman.conf
        line='Include = /etc/pacman.d/ansible.repos'
      notify: Update packages

    - name: Create file for each repo
      copy:
        content: |
          [{{item}}]
          Include = {{mirrorlist}}
        dest: /etc/pacman.d/repo.{{item}}
        owner: root
        group: root
        mode: 0644
      with_items: '{{repos}}'
      notify: Update packages

    - name: Master repo list
      template:
        src: templates/ansible.repos.j2
        dest: /etc/pacman.d/ansible.repos
        owner: root
        group: root
        mode: 0644
      notify: Update packages

  handlers:
    - name: Refresh keys
      command: pacman-key --refresh-keys

    - name: Update packages
      command: pacman -Syy
