- name: Aura and ABS
  hosts: arch
  vars:
    archbuilds: /opt/arch-builds
    build: '{{archbuilds}}/aura-bin'
    pkg: '{{build}}/aura-bin-1.3.4-1-x86_64.pkg.tar.xz'

  tasks:
    - name: Arch build system prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - fakeroot

    - name: Arch build system
      sudo: yes
      pacman: name=abs
      notify: set abs perms

    - name: AUR build dir
      file: path={{archbuilds}} state=directory owner=bhaskell group=bhaskell

    - name: Aura source
      git: repo=https://aur.archlinux.org/aura-bin.git
        dest={{build}}
        update=no
        remote=aur

    - name: Aura build package
      shell: makepkg -sr
        creates={{pkg}}
        chdir={{build}}

    - name: Aura install
      sudo: yes
      command: pacman --noconfirm -U {{pkg}}
        creates=/usr/sbin/aura

  handlers:
    - name: set abs perms
      command: set-all-facl -u -R /var/abs
