- name: Audio
  hosts: physical
  tasks:
    - name: PulseAudio network config
      lineinfile: dest=/etc/pulse/default.pa
        line='load-module module-{{item}}'
        regexp='module-{{item}}'
      with_items:
        - native-protocol-tcp
        - switch-on-connect

    - name: PulseAudio package
      become: true
      pacman:
        name: pulseaudio
      notify: restart pulseaudio

    - name: PulseAudio service
      systemd:
        name: pulseaudio
        user: yes
        state: started
        enabled: yes

  handlers:
    - name: restart pulseaudio
      systemd:
        name: pulseaudio
        user: yes
        state: restarted
