- name: Audio
  hosts: physical
  tasks:
    - name: PulseAudio network config
      lineinfile: dest=/etc/pulse/default.pa
        line='load-module module-{{item}}'
        regexp='module-{{item}}'
      with_items:
        - native-protocol-tcp
        - switch-on-connect
