- name: Audio
  hosts: physical
  tasks:
    - name: PulseAudio network config
      lineinfile: dest=/etc/pulse/default.pa
        line='load-module module-{{item}}'
        regexp='module-{{item}}'
      with_items:
        - native-protocol-tcp
        - switch-on-connect

    - name: PulseAudio package
      become: true
      pacman:
        name: pulseaudio
      notify: restart pulseaudio

    - name: PulseAudio service
      systemd:
        name: pulseaudio
        user: yes
        state: started
        enabled: yes

    - name: ALSA config for Nixpkgs (detect)
      shell: |
        nix-env -qas --out-path alsa-plugins 2>/dev/null |
        awk '/^.P/ { dir = $NF } END { if (dir) print dir }'
      register: nix_alsa_dir
      changed_when: False

    - name: ALSA config for Nixpkgs (file)
      become: true
      template:
        src: templates/asound.conf.j2
        dest: /etc/asound.conf
        owner: root
        group: root
        mode: 0644
      when: nix_alsa_dir.stdout != ""

  handlers:
    - name: restart pulseaudio
      systemd:
        name: pulseaudio
        user: yes
        state: restarted
