- name: Avahi (mDNS)
  hosts: arch
  become: true
  vars:
    prefix: 'hosts:'
  tasks:
    - name: Avahi packages
      pacman: name={{item}}
      with_items:
        - avahi
        - nss-mdns

    - name: Avahi services
      service: name={{item}} enabled=yes state=started
      with_items:
        - avahi-daemon
        - avahi-dnsconfd

    - name: .local resolution
      lineinfile: dest=/etc/nsswitch.conf
        regexp='^'{{prefix}}
        line='{{prefix}} files mdns_minimal [NOTFOUND=return] dns myhostname'
