- name: Bluetooth
  hosts: physical
  become: true
  tasks:
    - name: Bluetooth packages
      pacman: name={{item}}
      with_items:
        - bluez
        - bluez-utils
        - obexftp
        - ussp-push

    - name: Enable SDP compatibility
      lineinfile: dest=/usr/lib/systemd/system/bluetooth.service
        regexp='^ExecStart='
        line='ExecStart=/usr/lib/bluetooth/bluetoothd --compat'
      notify: restart bluetoothd

    - name: Bluetooth daemon
      service: name=bluetooth state=started enabled=yes

  handlers:
    - name: restart bluetoothd
      service: name=bluetooth state=restarted
