- name: Dev DNS
  hosts: arch
  become: true
  vars:
    bindir: /usr/local/bin
    exe: localdns
    force: false
    package: github.com/benizi/localdns
    systemd_dir: /etc/systemd/system

  tasks:
    - name: Install localdns prereqs
      pacman: name={{item}}
      with_items:
        - wicd
        - dhclient
        - openresolv # resolvconf

    - name: Configure resolvconf.conf and resolv.conf
      copy: content={{item.txt}}
        dest=/etc/{{item.base}}.conf
        owner=root group=root mode=0644
      with_items:
        - { base: resolvconf, txt: "resolv_conf=/etc/resolv.conf.upstream\n" }
        - { base: resolv, txt: "search internal\nnameserver 127.0.0.1\n" }

    - name: Ensure wicd uses dhclient
      lineinfile: dest=/etc/wicd/manager-settings.conf
        regexp='dhcp_client'
        line='dhcp_client = 1'
      notify: restart wicd

    - name: DHClient configuration
      copy: src=files/{{item}}
        dest=/etc/{{item}}
        owner=root
        group=root
        mode=0755
      with_items:
        - dhclient-enter-hooks
        - dhclient-exit-hooks

    - name: localdns binary
      become: false
      shell: |
        docker run --rm -it -v {{bindir}}:/out golang:1.8 sh -e -c '
        go get {{package}}
        go build -o /out/{{exe}} {{package}}'
      args:
        creates: '{{omit if force else "%s/%s" % (bindir, exe)}}'
      notify:
        - reload systemd
        - restart localdns

    - name: localdns service
      copy: src=files/{{item}}
        dest={{systemd_dir}}/{{item}}
      with_items: [localdns.service]
      notify:
        - reload systemd
        - restart localdns

    - name: localdns env
      template: src=templates/{{item}}.j2
        dest=/etc/{{item}}
      with_items: [localdns.env]
      notify:
        - reload systemd
        - restart localdns

    - name: localdns service
      service: name=localdns state=started enabled=yes

  handlers:
    - name: restart localdns
      service: name=localdns state=restarted

    - name: restart wicd
      service: name=wicd state=restarted

    - name: reload systemd
      command: systemctl daemon-reload
