- name: Dev servers
  hosts: laptops
  vars:
    pgdata: /var/lib/postgres/data

  tasks:
    - name: Install server packages
      become: true
      pacman: name={{item}}
      with_items:
        - mariadb
        - mongodb
        - nginx
        - postgresql
        - redis

    - name: Prevent system nginx
      become: true
      service: name=nginx state=stopped enabled=no

    - name: PostgreSQL initdb
      become: true
      command: su - postgres -c 'initdb --locale en_US.UTF-8 -D {{pgdata}}'
        creates={{pgdata}}/postgresql.conf

    - name: Start dev servers
      become: true
      service: name={{item}} state=started enabled=yes
      with_items:
        - postgresql
        - redis
