- name: Dev DNS
  hosts: arch
  vars:
    binary: /usr/local/bin/localdns
    systemd_dir: /etc/systemd/system

  tasks:
    - name: Install localdns prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - dhclient

    - name: Ensure wicd uses dhclient
      sudo: yes
      lineinfile: dest=/etc/wicd/manager-settings.conf
        regexp='dhcp_client'
        line='dhcp_client = 1'
      notify: restart wicd

    - name: DHClient configuration
      sudo: yes
      copy: src=files/{{item}}
        dest=/etc/{{item}}
        owner=root
        group=root
        mode=0755
      with_items:
        - dhclient-enter-hooks
        - dhclient-exit-hooks

    - name: localdns binary
      command: go build -o {{binary}} github.com/benizi/localdns
        creates={{binary}}

    - name: localdns service
      sudo: yes
      copy: src=files/{{item}}
        dest={{systemd_dir}}/{{item}}
      with_items: [localdns.service]
      notify:
        - reload systemd
        - restart localdns

    - name: localdns env
      sudo: yes
      template: src=templates/{{item}}.j2
        dest=/etc/{{item}}
      with_items: [localdns.env]
      notify:
        - reload systemd
        - restart localdns

    - name: localdns service
      sudo: yes
      service: name=localdns state=started enabled=yes

  handlers:
    - name: restart localdns
      sudo: yes
      service: name=localdns state=restarted

    - name: restart wicd
      sudo: yes
      service: name=wicd state=restarted

    - name: reload systemd
      sudo: yes
      command: systemctl daemon-reload
