- name: Dev servers
  hosts: laptops
  tasks:
    - name: Install server packages
      become: true
      pacman: name={{item}}
      with_items:
        - mariadb
        - mongodb
        - nginx
        - postgresql
        - redis

    - name: Prevent system versions
      become: true
      service: name={{item}} state=stopped enabled=no
      with_items:
        - nginx
        - postgresql
        - redis
