- name: Docker
  hosts: arch
  vars:
    confdir: /etc/systemd/system/docker.service.d

  tasks:
    - name: Install packages
      become: true
      pacman: name={{item}}
      with_items:
        - docker
        - docker-compose
        - docker-machine

    - name: Enable IPv4 forwarding
      become: true
      sysctl: name=net.ipv4.ip_forward value=1 sysctl_set=yes

    - name: Docker group
      become: true
      group: name=docker

    - name: Docker group (add me)
      become: true
      user: name=bhaskell
        append=yes
        groups=docker

    - name: Docker service settings directory
      become: true
      file: dest={{confdir}} state=directory owner=root group=root mode=0755
      notify: Reload Docker

    - name: Docker service files
      become: true
      template: src=templates/docker.service
        dest={{confdir}}/docker-options.conf
        owner=root group=root mode=0644
      notify:
        - reload systemd
        - Reload Docker

    - name: Docker enable services
      become: true
      service: name={{item}} state=started enabled=yes
      with_items:
        - docker.service
        - docker.socket

  handlers:
    - name: reload systemd
      become: true
      command: systemctl daemon-reload

    - name: Reload Docker
      become: true
      service: name=docker state=restarted
