- name: Docker
  hosts: arch
  vars:
    bindir: /usr/local/bin
    build: '{{gitbuild}}/docker'
    bundle: bundles/{{version}}/binary
    files:
      - dir: client
        base:
          - 'docker-{{version}}'
      - dir: daemon
        base:
          - 'dockerd-{{version}}'
          - docker-containerd
          - docker-containerd-ctr
          - docker-containerd-shim
          - docker-init
          - docker-proxy
          - docker-runc
    version: '1.13.0'

  tasks:
    - name: Install prereqs
      become: true
      pacman: name={{item}}
      with_items:
        # TODO: not sure these are needed for -e=native
        - bridge-utils
        - lxc

    - name: Docker source
      connection: local
      run_once: true
      git: repo=gh:docker/docker
        dest={{build}}
        version=v{{version}}
        remote=docker

    - name: Docker build
      connection: local
      run_once: true
      shell:
        cd {{build}} &&
        make &&
        sudo chown -R bhaskell bundles
        creates={{build}}/{{bundle}}-client/docker-{{version}}

    - name: Docker install
      synchronize: src={{build}}/{{bundle}}-{{item.0.dir}}/{{item.1}}
        dest={{bindir}}
        archive=no
        times=yes
      with_subelements:
        - '{{files}}'
        - base

    - name: Docker link
      file: state=link dest={{bindir}}/{{item}} src={{item}}-{{version}}
      with_items:
        - docker
        - dockerd

    - name: Enable IPv4 forwarding
      become: true
      sysctl: name=net.ipv4.ip_forward value=1 sysctl_set=yes

    - name: Docker group
      become: true
      group: name=docker

    - name: Docker group (add me)
      become: true
      user: name=bhaskell
        append=yes
        groups=docker

    - name: Docker service files
      become: true
      template: src=templates/docker.{{item}}
        dest=/etc/systemd/system/docker.{{item}}
      with_items: [service, socket]
      notify: reload systemd

    - meta: flush_handlers

    - name: Docker socket activation
      become: true
      service: name=docker.socket state=started enabled=yes

    - name: Docker service
      become: true
      service: name=docker.service enabled=yes

  handlers:
    - name: reload systemd
      become: true
      command: systemctl daemon-reload
