- name: Dotfiles
  hosts: laptops
  tasks:
    - name: Directories
      file: state=directory dest={{homedir}}/{{item}}
      with_items:
        - bin.local
        - .cache
        - .config
        - git
        - .lein
        - .urxvt
        - .vim.local
        - .zsh.local

    - name: Clone dotfiles
      git:
        repo: https://github.com/benizi/dotfiles
        dest: '{{homedir}}/dotfiles'
        update: no
        remote: benizi

    # TODO: replace this and the next task with script within dotfiles repo
    - name: Link dotfiles (simple)
      file: state=link src=dotfiles/{{item}} dest={{homedir}}/{{item}}
      with_items:
        - bin
        - .emacs.d
        - .gitattributes.global
        - .gitconfig
        - .gitignore.global
        - perl-lib
        - .pg
        - .psqlrc
        - .python
        - .terminfo
        - .tmux.conf
        - .Xdefaults
        - .xmonad
        - .xsession

    # TODO: see prior TODO
    - name: Link dotfiles (non-homedir)
      file: state=link src={{item.src}} dest={{homedir}}/{{item.dest}}
      with_items:
        - { src: ../dotfiles/.config/feh, dest: .config/feh }
        - { src: ../dotfiles/.lein/profiles.clj, dest: .lein/profiles.clj }
        - { src: ../dotfiles/.urxvt, dest: .urxvt/ext }
        - { src: dotfiles/.vim/vimrc, dest: .vimrc }
        - { src: dotfiles/.zsh/.zshenv, dest: .zshenv }

    - name: Root zsh
      become: true
      file: state=link src={{homedir}}/.zshenv dest=~root/.zshenv

    - name: Set up build for bin.local files
      file: state=link src=../bin/{{item}} dest={{homedir}}/bin.local/{{item}}
      with_items:
        - Makefile
        - src

    - name: Set shell
      become: true
      user: name=bhaskell shell=/bin/zsh
      when: inventory_hostname not in groups.osx

    - name: Script prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - inotify-tools
        - perl-algorithm-diff
        - perl-cgi
        - perl-date-manip
        - perl-fuse
        - perl-ipc-run
        - perl-json
        - perl-tk
        - perl-xml-twig
      when: inventory_hostname in groups.arch

    - name: Script prereqs (compiled)
      command: make {{item}}
        chdir={{homedir}}/bin.local
        creates={{item}}
      with_items:
        - myod
        - x-is-active
      when: inventory_hostname not in groups.osx
