- name: Install Dropbox
  hosts: arch
  tasks:
    - name: Dropbox package
      sudo: yes
      archpkg: name=aur/dropbox

    - name: Dropbox daemon install
      shell: echo y | dropbox start -i &&
        dropbox stop
        creates=~bhaskell/.dropbox-dist
