- name: Install Dropbox
  hosts: arch
  tasks:
    - name: Dropbox package
      become: true
      archpkg:
        name: aur/dropbox
        state: latest

    - name: Dropbox daemon install
      shell: echo y | dropbox start -i &&
        dropbox stop
        creates={{homedir}}/.dropbox-dist
