- name: Acceptable editors
  hosts: laptops
  vars:
    build: '{{gitbuild}}/vim'
  tasks:
    - name: Fallback (emacs)
      pacman: name={{item}}
      with_items:
        - emacs

    - name: Custom vim prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - lua51
        - tcl

    - name: Custom vim source
      git: repo='gh:benizi/vim'
        dest={{build}}
        version=24-bit
        remote=benizi
