- name: Install Feh (image viewer)
  hosts: arch
  vars:
    build: '{{gitbuild}}/feh'
    branch: auto-rotate-exif
    options: >
      exif=1
  tasks:
    - name: Feh (image viewer) prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - imlib2
        - giblib

    - name: Feh (image viewer) source
      git:
        repo: 'gh:benizi/feh'
        dest: '{{build}}'
        remote: benizi
        version: '{{branch}}'
        force: yes
      notify: install feh

  handlers:
    - name: install feh
      shell: |
        set -e
        make {{options}}
        make install
      args:
        chdir: '{{build}}'
