- name: Install Feh (image viewer)
  hosts: arch
  vars:
    build: '{{gitbuild}}/feh'
  tasks:
    - name: Feh (image viewer) prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - imlib2
        - giblib

    - name: Feh (image viewer) source
      git: repo=gh:benizi/feh
        dest={{build}}
        remote=benizi
      notify: install feh

  handlers:
    - name: install feh
      shell: make && make install
        chdir={{build}}
