- name: Google Chrome Latest
  hosts: arch
  vars:
    update: false
    track: unstable
    pkg:
      name: google-chrome-{{track}}
      version: '62.0.3198.0'
      release: '-1'
      sha256: a4b5b845ad804215dae33cddf8da8ef122520b215c38a1b9bab0ebf431c2a534
    cache: "{{gitbuild}}/{{pkg.name}}.deb"
    packages: "{{gitbuild}}/google-chrome.Packages"
    latest: "{{cache}}.latest"
    prefix: '/opt/google/chrome/{{pkg.version}}'
    debroot: https://dl.google.com/linux/chrome/deb
    packagesurl: '{{debroot}}/dists/stable/main/binary-amd64/Packages'
    basename: '{{pkg.name}}_{{pkg.version}}{{pkg.release}}_amd64.deb'
    debpath: 'pool/main/g/{{pkg.name}}/{{basename}}'
    url: '{{debroot}}/{{pkg.filename|default(debpath)}}'
    # strip components = 4 (including `.`): ./opt/google/chrome-{{track}}/
    stripcomponents: 4

  tasks:
    - name: Find latest Chrome version info
      get_url:
        url: '{{packagesurl}}'
        dest: '{{packages}}'
        force: '{{update}}'
      check_mode: no

    - name: Update version info from Packages
      shell: |
        awk -F': ' '
        $1 == "Package" { print "{" }
        $1 ~ /^(Package|Version|Filename|SHA256)$/ {
          print "\"" $1 "\":\"" $2 "\""
          print $1 == "SHA256" ? "}" : ","
        }' {{packages}} |
        jq 'with_entries(.key|=({Package:"name"}[.]//ascii_downcase)) |
        select(.name=="{{pkg.name}}") |
        (.version/"-") as $v | . + {version: $v[0], release: ("-" + $v[1])}'
      register: findversion
      changed_when: false
      check_mode: no
      when: update

    - name: Update package attributes
      set_fact:
        pkg: '{{findversion.stdout|from_json}}'
      when: update

    - name: Download latest version
      get_url:
        dest: '{{cache}}'
        url: '{{url}}'
        checksum: 'sha256:{{pkg.sha256}}'

    - name: Install latest version
      shell: |
        set -e
        mkdir -p {{prefix}}
        deb2targz {{cache}} |
        tar Jx -C {{prefix}} --strip-components={{stripcomponents}} ./opt
      args:
        creates: '{{prefix}}/chrome'
