- name: Heroku Toolbelt
  hosts: arch
  vars:
    cache: '{{gitbuild}}/{{targz}}'
    dir: /usr/local/heroku
    os: linux
    arch: x64
    targz: 'heroku-cli-{{os}}-{{arch}}.tar.gz'
    url: 'https://cli-assets.heroku.com/heroku-cli/channels/stable/{{targz}}'

  tasks:
    - name: Heroku CLI download
      get_url:
        url: '{{url}}'
        dest: '{{cache}}'

    - name: Heroku CLI directory
      file: dest={{dir}} state=directory

    - name: Heroku CLI install
      command: tar -C {{dir}} --strip-components 1 -xf {{cache}}
        creates={{dir}}/bin/heroku

    - name: Heroku CLI plugins
      command: heroku plugins:install {{item.git}}
        creates={{homedir}}/.heroku/plugins/{{item.name}}
      with_items:
        - name: 'heroku-accounts'
          git: 'https://github.com/heroku/heroku-accounts.git'

        - name: 'heroku-anvil'
          git: 'https://github.com/ddollar/heroku-anvil'

        - name: 'heroku-redis-cli'
          git: 'https://github.com/rapportive-oss/heroku-redis-cli.git'

        - name: 'heroku-repo'
          git: 'https://github.com/heroku/heroku-repo.git'

        - name: 'heroku-alternative-urls'
          git: 'https://github.com/benizi/heroku-alternative-urls.git'
