- name: Monitor
  hosts: physical
  vars:
    dbbuild: '{{gitbuild}}/ddccontrol-db'
    toolbuild: '{{gitbuild}}/ddccontrol'
    destroot: /opt/ddccontrol
  tasks:
    - name: DDC/CI tool source
      git: repo='gh:benizi/ddccontrol'
        dest={{toolbuild}}
        version=automated-build
        remote=benizi
        update=no

    - name: DDC/CI monitor database source
      git: repo='gh:benizi/ddccontrol-db'
        dest={{dbbuild}}
        remote=benizi
        update=no

    - name: DDC/CI tool install
      shell: ./autogen.sh &&
        ./configure --prefix={{destroot}} &&
        make &&
        make install
        chdir={{item.build}}
        creates={{item.creates}}
      with_items:
        - { build: '{{toolbuild}}', creates: '{{destroot}}/bin/ddccontrol' }
        - { build: '{{dbbuild}}', creates: '{{destroot}}/share/ddccontrol-db' }

    - name: i2c kernel module
      copy: content='i2c-dev\n'
        dest=/etc/modules-load.d/ddccontrol.conf
        mode=0640

    - name: Other i2c tools
      pacman: name=i2c-tools
      become: yes
