- name: MOSH (SSH alternative)
  hosts: all
  vars:
    build: '{{gitbuild}}/mosh'
  tasks:
    - name: MOSH prereqs (EC2)
      become: true
      yum: name={{item}}
        enablerepo=epel
      with_items:
        - automake
        - gcc-c++
        - protobuf-compiler
        - protobuf-devel
        - libutempter-devel
        - ncurses
        - ncurses-devel
        - zlib-devel
        - boost-devel
      when: ansible_distribution == 'Amazon'

    - name: MOSH prereqs (non-EC2)
      become: true
      pacman: name={{item}}
      with_items:
        - protobuf
      when: ansible_distribution == 'Archlinux'

    - name: MOSH source
      git: repo=https://github.com/keithw/mosh
        dest={{build}}
        remote=keithw

    - name: MOSH install
      shell: sh ./autogen.sh &&
        ./configure &&
        make &&
        make install
        chdir={{build}}
        creates=/usr/local/bin/mosh-server
