- name: Networking
  hosts: arch
  become: true
  vars:
    rulesdir: /etc/polkit-1/rules.d

  tasks:
    - name: Prevent mismatched libnm version
      # Exit with failure if more than one version is installed or available
      shell: |
        {
          pacman -Qi libnm 2>/dev/null
          pacman -Si libnm networkmanager 2>/dev/null
        } | grep '^Version' | sort | uniq | awk 'END { exit (NR > 1) ? 1 : 0 }'
      register: libnm_version
      changed_when: libnm_version|failed
      failed_when: false
      always_run: true
      notify: Update libnm

    - meta: flush_handlers

    - name: Install NetworkManager
      pacman: name={{item}}
      with_items:
        - networkmanager
        - network-manager-applet

    - name: NetworkManager Polkit rule
      copy: src=files/networkmanager.polkit.rules
        dest={{rulesdir}}/20-networkmanager.rules
        owner=root group=root mode=0644
      notify: Reload Polkit

    - name: NetworkManager prevent DNS interference
      lineinfile: dest=/etc/NetworkManager/NetworkManager.conf
        regexp={{item.regexp}}
        line={{item.line}}
      with_items:
        - { regexp: '^\[', line: '[main]' }
        - { regexp: '^rc-manager=', line: 'rc-manager=resolvconf' }
      notify: Restart NetworkManager

    - name: NetworkManager service
      service: name=NetworkManager state=started enabled=yes
      notify: Restart NetworkManager

    - meta: flush_handlers

    - name: Verify inactive wicd
      command: systemctl show wicd -t service -p UnitFileState --value
      register: current
      always_run: true
      changed_when: current.stdout_lines == ['enabled']
      failed_when: false
      notify: Disable wicd

  handlers:
    - name: Update libnm
      pacman: name={{item}} state=latest
      with_items:
        - libnm
        - libnm-glib

    - name: Reload Polkit
      command: pkill -HUP polkitd
      ignore_errors: true

    - name: Restart NetworkManager
      service: name=NetworkManager state=restarted

    - name: Disable wicd
      service: name=wicd state=stopped enabled=no
      register: service
      changed_when: service|changed and not service|failed
      failed_when: service|failed and service.msg.find('could not find') < 0
