- name: Nix
  hosts: arch
  vars:
    prefix: /opt/nix
    version: 1.11.8

  tasks:
    - name: Nix prereqs
      pacman: name={{item}}
      become: true
      with_items:
        - perl-dbd-sqlite
        - perl-www-curl

    - name: Nix directory
      file: path=/nix state=directory owner=bhaskell group=bhaskell mode=0700
      become: true

    - name: Nix package manager source
      get_url: url=http://nixos.org/releases/nix/nix-{{version}}/nix-{{version}}.tar.xz
        dest={{gitbuild}}/nix-{{version}}.tar.xz

    - name: Nix package manager install
      shell: |
        set -e
        export PATH="{{prefix}}/bin:$PATH"
        if hash nix-build 2>/dev/null && nix-build --version >/dev/null
        then echo ok ; exit 0
        fi
        cd {{gitbuild}}
        rm -rf nix-{{version}}
        tar xJf {{gitbuild}}/nix-{{version}}.tar.xz
        cd nix-{{version}}
        ./configure --prefix={{prefix}}
        make
        make install
      register: install
      changed_when: install.stdout_lines != ["ok"]
