- name: Nix
  hosts: arch
  vars:
    prefix: /opt/nix
    version: 1.11.16
    dirname: 'nix-{{version}}'
    filename: '{{dirname}}.tar.xz'

  tasks:
    - name: Nix prereqs
      pacman: name={{item}}
      become: true
      with_items:
        - perl-dbd-sqlite
        - perl-www-curl

    - name: Nix directory
      file: path=/nix state=directory owner=bhaskell group=bhaskell mode=0700
      become: true

    - name: Nix package manager source
      get_url:
        url: 'http://nixos.org/releases/nix/{{dirname}}/{{filename}}'
        dest: '{{gitbuild}}/{{filename}}'

    - name: Nix package manager install
      shell: |
        set -e
        export PATH="{{prefix}}/bin:$PATH"
        if hash nix-build 2>/dev/null && nix-build --version |
          grep -Fxq "nix-build (Nix) {{version}}"
        then echo ok ; exit 0
        fi
        cd {{gitbuild}}
        rm -rf {{dirname}}
        tar xJf {{gitbuild}}/{{filename}}
        cd nix-{{version}}
        ./configure --prefix={{prefix}}
        make
        make install
      register: install
      changed_when: install.stdout_lines != ["ok"]
