- name: Nix
  hosts: arch
  vars:
    version: 1.11.2

  tasks:
    - name: Nix prereqs
      pacman: name={{item}}
      become: true
      with_items:
        - perl-dbd-sqlite
        - perl-www-curl

    - name: Nix package manager source
      get_url: url=http://nixos.org/releases/nix/nix-{{version}}/nix-{{version}}.tar.xz
        dest={{gitbuild}}/nix-{{version}}.tar.xz

    - name: Nix package manager install
      shell: cd {{gitbuild}} &&
        rm -rf nix-{{version}} &&
        tar xJf {{gitbuild}}/nix-{{version}}.tar.xz &&
        cd nix-{{version}} &&
        ./configure --prefix=/opt/nix &&
        make &&
        make install
        creates=/opt/nix/bin/nix-build
        warn=no
