- name: Set up NTP
  hosts: all
  become: true
  tasks:
    - name: Set up NTP
      service: name=ntpd state=started enabled=yes
      when: ntp
      notify:
        # Set the clock upon initial ntpd setup
        - stop ntpd
        - set clock
        - start ntpd

  handlers:
    - name: Stop existing
      service: name=ntpd state=stopped

    - name: Set clock initially
      command: ntpdate -s time.nist.gov

    - name: Restart NTP after setting clock
      service: name=ntpd state=started
