- name: OSX Stuff
  hosts: osx
  vars:
    brewurl: https://raw.githubusercontent.com/Homebrew/install/{{commit}}/install
    commit: d97fb9edbe2ea308400a894f7d1df7967717a937
    script: ~/.homebrew.install.rb
    sha256sum: 1a48258db024391a7864c155c9b6076744c18d39cd7403b04545881bda01f4a8
  tasks:
    - name: Workaround stupid path_helper
      copy:
        content: |
          eval "$(/usr/libexec/path_helper -s)" 2>/dev/null
        dest: ~/.bashrc
        mode: 0750

    - name: Homebrew install script
      get_url:
        dest: '{{script}}'
        url: '{{brewurl}}'
        sha256sum: '{{sha256sum}}'

    - name: Install homebrew
      shell: |
        if hash brew >/dev/null 2>/dev/null
        then echo already
        else ruby {{script}}
        fi
      register: install
      changed_when: install.stdout_lines != ['already']
      failed_when: install.rc != 0
