- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: FUSE permissions
      lineinfile:
        dest: /etc/fuse.conf
        regexp: user_allow_other
        line: user_allow_other

    - name: Remote filesystems
      pacman: name={{item}}
      with_items:
        - smbclient
        - sshfs
