- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Multimedia
      pacman: name={{item}}
      with_items:
        - kodi
        - libdvdcss # DVD decryption
        - mencoder # split from `mplayer`
        - minidlna
        - mplayer
        - mpv # mplayer fork
        - qt5-multimedia # common dependency
        - vlc
