- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Programmer tools
      archpkg: name={{item}}
      with_items:
        - ack
        - dtach
        - jq
        - meld
        - python2-yapf
        - aur/rescuetime
        - screen
        - tmux
        - x11vnc
        - xorg-server-xephyr
        - xorg-server-xvfb
