- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Fonts
      archpkg: name={{item}}
      with_items:
        - aur/ttf-font-awesome
        - fontforge
        - gsfonts
        - aur/ttf-monoid
        - aur/otf-fira-code-git
        - otf-fira-mono
        - otf-ipafont
        - opendesktop-fonts
        - ttf-bitstream-vera
        - ttf-dejavu
        - wqy-zenhei
