- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Programmer tools
      archpkg: name={{item}}
      with_items:
        - ack
        - dtach
        - jq
        - libxml2 # for xmllint
        - meld
        - pv # pipe viewer
        - python2-yapf
        - aur/rescuetime
        - rlwrap
        - screen
        - tidy
        - tmux
        - unoconv # deal with MS Office formats
        - x11vnc
        - xorg-server-xephyr
        - xorg-server-xvfb
