- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Remove BIND cruft
      pacman: name=bind-tools state=absent

    - name: Golang `dig` replacement
      become: false
      shell: |
        set -e
        cd {{homedir}}/bin.local
        test -e dig || make dig
      register: build
      changed_when: build.stdout != ''

    - name: System tools
      archpkg: name={{item}}
      with_items:
        - gdb
        - htop
        - iotop
        - iw
        - kexec-tools
        - ldns # for drill
        - lsof
        - ltrace
        - nmap
        - ovmf # UEFI firware for qemu
        - rsync
        - smartmontools # for `smartctl`
        - socat
        - strace
        - sysstat
        - systemtap # for `stap`
        - tcpflow # capture TCP traffic
        - tftp-hpa # TFTP client for testing
        - words
