- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: System tools
      archpkg: name={{item}}
      with_items:
        - bind-tools
        - aur/daemontools
        - gdb
        - htop
        - iotop
        - iw
        - lsof
        - ltrace
        - nmap
        - rsync
        - socat
        - strace
        - sysstat
        - words
