- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Audio
      archpkg: name={{item}}
      with_items:
        - ardour
        - aur/spotify
        - festival-us
        - fluidsynth
        - id3lib
        - soundfont-fluid
        - lilypond
        - pavucontrol
        - pulseaudio-alsa
        - pulseaudio-jack
        - sox
