- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Compression
      pacman: name={{item}}
      with_items:
        - cpio
        - p7zip
        - squashfs-tools
        - unarj
        - unrar
        - unzip
        - zip
