- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Graphics
      pacman: name={{item}}
      with_items:
        - blender
        - ghostscript
        - gimp
        - graphicsmagick
        - graphviz
        - imagemagick
        - inkscape
        - maim # screenshot tool
        - perl-image-exiftool
        - poppler # PDF handling
        - slop # region selector
