- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Shells
      pacman: name={{item}}
      with_items:
        - bash
        - dash # much POSIX
        - fish # I hate `fish`, but people use it
        - mksh # MirBSD ksh
        - tcsh
