- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: FUSE permissions
      lineinfile:
        dest: /etc/fuse.conf
        regexp: user_allow_other
        line: user_allow_other

    - name: Remote filesystems
      pacman: name={{item}}
      with_items:
        - smbclient
        - sshfs

    - name: NBD package
      pacman:
        name: nbd # network block device
      notify: restart nbd

    - name: NBD service
      service:
        name: nbd
        state: started
        enabled: yes

    - name: iSCSI Target package
      aura:
        name: targetcli-fb
      notify: restart target

    - name: iSCSI Target service
      service:
        name: target
        state: started
        enabled: yes

  handlers:
    - name: restart target
      service:
        name: target
        state: restarted

    - name: restart nbd
      service:
        name: nbd
        state: restarted
