- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Browsers
      archpkg: name={{item}}
      with_items:
        - chromium
        - firefox
        - aur/firefox-esr-bin # for NPAPI plugin support
        - npapi-vlc
        - opera
        - w3m
