- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: Multimedia
      pacman: name={{item}}
      with_items:
        - kodi
        - minidlna
        - mplayer
        - vlc
