- name: Install many packages
  hosts: arch
  become: true
  tasks:
    - name: X11 utilities
      pacman: name={{item}}
      with_items:
        - lxpanel
        - mesa-demos # glxinfo and glxgears
        - parcellite
        - rofi # dmenu-replacement
        - xclip
        - xorg-xbacklight
        - xorg-xdpyinfo
        - xorg-xev
        - xorg-xwininfo
        - xosd
