- name: Password manager
  hosts: laptops
  tasks:
    - name: Install password-manager prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - gnome-keyring
        - libgnome-keyring

    - name: build password-manager
      command: make password-manager
        chdir=~bhaskell/bin.local
        creates=password-manager
