- name: Personal directories
  hosts: laptops
  tasks:
    - name: Own some 'system' directories
      shell: find {{item}} -xdev -maxdepth 1 2>&1 >/dev/null | grep -L . | grep -q . ||
        set-all-facl u:bhaskell -v -R {{item}}
      with_items:
        - /mnt
        - /opt
        - /usr/local
      register: dirs
      changed_when: dirs.stdout != ''

    - name: Own /etc but skip ssh
      shell: if find /etc -xdev -type d ! -writable | grep -qvxF /etc/ssh; then
        set-all-facl u:bhaskell -v -R /etc &&
        sudo setfacl -R -b /etc/ssh &&
        sudo chmod -R go-rwx /etc/ssh/*_key &&
        sudo chmod -R go+r /etc/ssh/*.pub; fi
      register: etc
      changed_when: etc.stdout != ''
