- name: Prereqs
  hosts: arch
  become: true
  tasks:
    # conflicts with `vim-minimal` (initially) and `gvim` (later)
    - name: Remove conflicting Vim version
      pacman: name=vim state=absent

    - name: Very basic prereqs
      pacman: name={{item}}
      with_items:
        - git
        - ntp
        - polkit
        - zsh

    - name: Detect whether vim-minimal is needed
      shell: pacman -T gvim || pacman -T vim-minimal
      register: hasvim
      changed_when: hasvim.rc != 0
      failed_when: false

    - name: Minimal Vim for bootstrapping
      pacman: name=vim-minimal
      when: hasvim|changed

    - name: X Server prereqs
      pacman: name={{item}}
      with_items:
        - xorg-server
        - xf86-video-intel
        - xf86-input-evdev
        - xf86-input-keyboard
        - xf86-input-mouse
        - xf86-input-synaptics
        - xorg-xauth

    - name: X-related idiosyncratic prereqs
      pacman: name={{item}}
      with_items:
        - unclutter
        - xbindkeys
        - xdotool
        - xorg-twm # fallback window manager
        - xorg-xinput
        - xorg-xmodmap
        - xorg-xprop
        - xorg-xrandr
        - xorg-xsetroot
