- name: Prereqs
  hosts: arch
  sudo: true
  tasks:
    - name: Very basic prereqs
      pacman: name={{item}}
      with_items:
        - git
        - ntp
        - polkit
        - vim-minimal
        - zsh

    - name: X Server prereqs
      pacman: name={{item}}
      with_items:
        - xorg-server
        - xf86-video-intel
        - xf86-input-evdev
        - xf86-input-keyboard
        - xf86-input-mouse
        - xf86-input-synaptics
        - xorg-xauth

    - name: X-related idiosyncratic prereqs
      pacman: name={{item}}
      with_items:
        - unclutter
        - xbindkeys
        - xdotool
        - xorg-twm # fallback window manager
        - xorg-xinput
        - xorg-xmodmap
        - xorg-xprop
        - xorg-xrandr
        - xorg-xsetroot

    - name: Idiosyncratic prereqs # mostly for old Perl scripts
      pacman: name={{item}}
      with_items:
        - perl-fuse
        - perl-ipc-run
        - perl-json
        - perl-tk
