- name: Prereqs
  hosts: arch
  become: true
  tasks:
    # Versions of `vi`-like editors on Arch currently:
    # - `vi` = minimal `vi`-clone (useful for bootstrapping)
    # - `vim-minimal` = Vim "tiny" build (now deleted)
    # - `vim` = terminal-only "full" Vim (lacks `+clipboard`)
    # - `gvim` = Vim and GVim (where Vim includes `+clipboard`)
    - name: Remove conflicting/outdated Vim versions
      pacman: name={{item}} state=absent
      with_items:
        - vim
        - vim-minimal

    - name: Remove outdated Intel Xorg driver
      pacman:
        name: xf86-video-intel
        state: absent

    - name: Very basic prereqs
      pacman: name={{item}}
      with_items:
        - git
        - ntp
        - opensc # for pkcs11-tool
        - openssl
        - polkit
        - vi
        - zsh

    - name: X Server prereqs
      pacman: name={{item}}
      with_items:
        - xorg-server
        - xf86-input-evdev
        - xf86-input-keyboard
        - xf86-input-mouse
        - xf86-input-synaptics
        - xorg-xauth

    - name: X-related idiosyncratic prereqs
      pacman: name={{item}}
      with_items:
        - unclutter # auto-hide mouse pointer
        - xbindkeys
        - xdotool
        - xorg-twm # fallback window manager
        - xorg-xinput
        - xorg-xmodmap
        - xorg-xprop
        - xorg-xrandr
        - xorg-xsetroot
