- name: Software Defined Radio
  hosts: sdr
  vars:
    confdir: '{{homedir}}/.gnuradio'

  tasks:
    - name: GNU Radio
      archpkg: name={{item}}
      with_items:
        - gnuradio
        - gnuradio-osmosdr
        - gnuradio-companion

    - name: GNU Radio config dir
      file: dest={{confdir}} state=directory

    - name: GNU Radio fix Pulse
      ini_file: dest={{confdir}}/config.conf
        section=audio_alsa
        option=nperiods
        value=128
