- name: Remote access tools
  hosts: laptops
  vars:
    tag: v-enable-scroll-lock
    cache: '{{gitbuild}}/synergy.tar.gz'

  tasks:
    - name: VNC and RDP
      sudo: yes
      pacman: name={{item}}
      with_items:
        - freerdp
        - gtk-vnc
        - x11vnc

    - name: Custom synergy prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - qt4

    - name: Custom synergy source
      get_url: url=https://github.com/benizi/synergy/archive/{{tag}}.tar.gz
        dest={{cache}}
        sha256sum=bc0863b0352f536473cd860b86bfcd09b345ec9fa55b3510ae595796d0e770f8

    - name: Custom synergy install
      shell: rm -rf /tmp/synergy-{{tag}} &&
        tar zxf {{cache}} &&
        cd synergy-{{tag}} &&
        with-python2 ./hm.sh conf -g1 &&
        with-python2 ./hm.sh build &&
        mv bin/synergy{c,d,s} ~bhaskell/bin.local/
        chdir=/tmp
        creates=~bhaskell/bin.local/synergyc
