- name: Remote access tools
  hosts: laptops
  vars:
    tag: add-audio-pause-x11
    cache: '{{gitbuild}}/synergy-{{tag}}.tar.gz'
    sha256sum: 8062a2dcbab760dd561e56e4487fd4ea77b8475ccf2ed80c3b6c6d47fa1de778
    prefix: '{{homedir}}/.local/bin'

  tasks:
    - name: VNC and RDP
      become: true
      pacman: name={{item}}
      with_items:
        - freerdp
        - gtk-vnc
        - x11vnc

    - name: Custom synergy prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - qt4

    - name: Custom synergy source
      get_url: url=https://github.com/benizi/synergy/archive/{{tag}}.tar.gz
        dest={{cache}}
        sha256sum={{sha256sum}}

    - name: Custom synergy install
      shell: |
        set -e
        rm -rf build-synergy synergy-{{tag}}
        mkdir build-synergy
        tar zxf {{cache}}
        cd build-synergy
        set -- -DSYNERGY_BUILD_LEGACY_{GUI,SERVICE,INSTALLER}=OFF
        cmake "$@" -g1 ../synergy-{{tag}}
        make
        mv bin/synergy{c,s} {{prefix}}
      args:
        chdir: /tmp
        creates: '{{prefix}}/synergyc'
        warn: no
