- name: Custom s3cmd
  hosts: arch
  vars:
    build: '{{gitbuild}}/s3cmd'
  tasks:
    - name: Custom s3cmd source
      git: repo=gh:benizi/s3cmd
        dest={{build}}
        version=feature/fog-config
        update=no
        remote=benizi

    - name: Custom s3cmd wrapper
      copy: content='#!/bin/sh\nexec python2 {{build}}/s3cmd "$@"'
        dest={{homedir}}/bin.local/s3cmd
        mode=0750
