- name: Custom s3cmd
  hosts: arch
  vars:
    branch: customized
    build: '{{gitbuild}}/s3cmd'
    update: false
  tasks:
    - name: Custom s3cmd source
      git:
        repo: 'gh:benizi/s3cmd'
        dest: '{{build}}'
        version: '{{branch}}'
        update: '{{update}}'
        remote: 'benizi'

    - name: Custom s3cmd wrapper
      copy: content='#!/bin/sh\nexec python2 {{build}}/s3cmd "$@"'
        dest={{homedir}}/bin.local/s3cmd
        mode=0750
