---
- name: Arch packaging
  hosts: arch
  sudo: true
  vars:
    mirrorlist: /etc/pacman.d/mirrorlist
    repos: [testing, core, extra, community, multilib]

  tasks:
    - name: Disable all repos (no includes)
      lineinfile: dest=/etc/pacman.conf
        state=absent
        regexp='^Include\s*=\s*{{mirrorlist}}\s*$'
      notify: Update packages

    - name: Disable all repos (no sections)
      lineinfile: dest=/etc/pacman.conf
        line='#[{{item}}]'
        regexp='\[{{item}}\]'
      with_items: repos
      notify: Update packages

    - name: Add include for chosen repos
      lineinfile: dest=/etc/pacman.conf
        line='Include = /etc/pacman.d/repo.*'
      notify: Update packages

    - name: Create files for each repo
      copy: content='[{{item.1}}]\nInclude = {{mirrorlist}}\n'
        dest=/etc/pacman.d/repo.{{item.0}}.{{item.1}}
        owner=root
        group=root
        mode=0644
      with_indexed_items: repos
      notify: Update packages

    - name: Atlassian repo
      copy: src=files/atlassian.repo
        dest=/etc/pacman.d/repo.atlassian
        owner=root
        group=root
        mode=0644
      notify:
        - Atlassian key
        - Update packages

  handlers:
    - name: Atlassian key
      shell: curl https://www.hipchat.com/keys/hipchat-linux.key |
        GNUPGHOME=/etc/pacman.d/gnupg gpg --import

    - name: Update packages
      command: pacman -Syy

- name: Prereqs
  hosts: arch
  sudo: true
  tasks:
    - name: Very basic prereqs
      pacman: name={{item}}
      with_items:
        - git
        - ntp
        - polkit
        - vim-minimal
        - zsh

    - name: X Server prereqs
      pacman: name={{item}}
      with_items:
        - xorg-server
        - xf86-video-intel
        - xf86-input-evdev
        - xf86-input-keyboard
        - xf86-input-mouse
        - xf86-input-synaptics
        - xorg-xauth

    - name: X-related idiosyncratic prereqs
      pacman: name={{item}}
      with_items:
        - perl-ipc-run # for my keyboard wrapper
        - xdotool
        - xorg-twm # fallback window manager
        - xorg-xinput
        - xorg-xmodmap
        - xorg-xprop
        - xorg-xrandr

- name: Set up NTP
  hosts: all
  sudo: true
  tasks:
    - name: Set up NTP
      service: name=ntpd state=started enabled=yes
      register: ntp

    # next tasks set the clock initially
    - name: Stop existing
      service: name=ntpd state=stopped
      when: ntp.changed

    - name: Set clock initially
      command: ntpdate -s time.nist.gov
      when: ntp.changed

    - name: Restart NTP after setting clock
      service: name=ntpd state=started
      when: ntp.changed

- name: Initial .ssh/config
  hosts: all
  tasks:
    - name: .ssh/config
      copy: content="Host gh\nHostName github.com\nUser git\n"
        dest=.ssh/config
        force=no

    - name: SSH known hosts
      sudo: yes
      copy: src=files/ssh_known_hosts
        dest=/etc/ssh/ssh_known_hosts
        owner=root
        group=root
        mode=0644

- name: Development
  hosts: arch # TODO: others
  sudo: true
  tasks:
    - name: Standard compiling prereqs
      pacman: name={{item}}
      with_items:
        - autoconf
        - cmake
        - gcc
        - make
        - pkg-config

- name: Custom dmenu
  hosts: arch
  vars:
    dmenu: git/dmenu

  tasks:
    - name: Custom dmenu source
      git: repo='gh:benizi/dmenu'
        dest={{dmenu}}

    - name: Custom dmenu build
      shell: make && make install
        chdir={{dmenu}}
        creates=/usr/local/bin/dmenu

- name: XMonad
  hosts: arch
  tasks:
    - name: XMonad prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - dzen2 # status bars
        - ghc
        - ruby # needed for scripts, will be overridden later
        - xlockmore # screensaver
        - xorg-xdm
        - xorg-xmessage

    - name: Cabal (Haskell package manager)
      sudo: yes
      pacman: name=cabal-install
      notify: Set up cabal

    - meta: flush_handlers

    - name: Cabal packages
      command: cabal install {{item}}
      with_items:
        - darcs
        - FindBin
        - xmonad
        - xmonad-contrib

    - name: Enable services
      sudo: yes
      service: name=xdm state=started enabled=yes

  handlers:
    - name: Set up cabal
      command: cabal update

- name: Dotfiles
  hosts: laptops
  tasks:
    - name: Directories
      file: state=directory dest=~bhaskell/{{item}}
      with_items:
        - bin.local
        - .cache
        - git
        - .vim.local
        - .zsh.local

    - name: Clone latest dotfiles
      git: repo=https://github.com/benizi/dotfiles dest=dotfiles update=yes

    # TODO: replace this with script within dotfiles repo
    - name: Link dotfiles
      file: state=link
        src=dotfiles/{{item.src}}
        dest={{item.dest | default(item.src)}}
      with_items:
        - { src: bin }
        - { src: .emacs.d }
        - { src: .gitattributes.global }
        - { src: .gitconfig }
        - { src: .gitignore.global }
        - { src: .terminfo }
        - { src: .tmux.conf }
        - { src: .urxvt }
        - { src: .vim/vimrc, dest: .vimrc }
        - { src: .Xdefaults }
        - { src: .xmonad }
        - { src: .xsession }
        - { src: .zsh/.zshenv, dest: .zshenv }

    - name: Root zsh
      sudo: yes
      file: state=link src=~bhaskell/.zshenv dest=~root/.zshenv

    - name: Set up build for bin.local files
      file: state=link src=../bin/{{item}} dest=bin.local/{{item}}
      with_items:
        - Makefile
        - src

    - name: Set shell
      sudo: true
      user: name=bhaskell shell=/bin/zsh

    - name: Script prereqs
      sudo: true
      pacman: name={{item}}
      with_items:
        - inotify-tools
        - perl-algorithm-diff
        - perl-cgi
        - perl-date-manip

- name: Personal directories
  hosts: laptops
  tasks:
    - name: Own some 'system' directories
      sudo: true
      file: dest={{item}}
        state=directory
        owner=bhaskell
        group=bhaskell
        recurse=yes
      with_items:
        - /opt
        - /usr/local

- name: Acceptable terminal emulators
  hosts: laptops
  vars:
    rxvt_git: git/rxvt-unicode
    rxvt: /usr/local/bin/urxvt

  tasks:
    - name: Fallback (xterm and standard rxvt-unicode)
      sudo: true
      pacman: name={{item}}
      with_items:
        - rxvt-unicode
        - xterm

    - name: Preferred (custom rxvt-unicode) prereqs
      sudo: true
      pacman: name={{item}}
      with_items:
        - cvs # for external libs
        - libev

    - name: Preferred (custom rxvt-unicode) source
      git: repo='gh:benizi/rxvt-unicode'
        dest={{rxvt_git}}
        version=24bit

    - name: Preferred (custom rxvt-unicode) CVS libs
      command: cvs -z3 -d :pserver:anonymous@cvs.schmorp.de/schmorpforge co {{item}}
        chdir={{rxvt_git}}
        creates={{item}}
      with_items:
        - libev
        - libptytty

    - name: Preferred (custom rxvt-unicode) build
      shell: sh ./autogen.sh &&
        autoreconf &&
        ./configure --enable-24-bit-color --enable-xft --enable-perl --enable-256-color --disable-iso14755 &&
        make -j{{ansible_processor_vcpus}} &&
        make install
        chdir={{rxvt_git}}
        creates={{rxvt}}

    - name: Preferred (custom rxvt-unicode) link
      file: dest=bin.local/term state=link src={{rxvt}}

- name: Acceptable editors
  hosts: laptops
  tasks:
    - name: Fallback (emacs)
      pacman: name={{item}}
      with_items:
        - emacs

    - name: Preferred (custom vim) prereqs
      sudo: true
      pacman: name={{item}}
      with_items:
        - lua51
        - tcl

    - name: Preferred (custom vim) source
      git: repo='gh:benizi/vim'
        dest=git/vim
        version=24-bit

    - name: Preferred (custom vim) install
      command: build-vim
        chdir=git/vim
        creates=/usr/local/bin/vim

- name: Install many packages
  hosts: arch
  sudo: yes
  tasks:
    - name: System tools
      pacman: name={{item}}
      with_items:
        - dnsutils
        - htop
        - iotop
        - lsof
        - nmap
        - rsync
        - socat
        - strace

    - name: Audio
      pacman: name={{item}}
      with_items:
        - festival-us
        - pavucontrol
        - pulseaudio-alsa

    - name: Fonts
      pacman: name={{item}}
      with_items:
        - otf-ipafont
        - opendesktop-fonts
        - ttf-bitstream-vera
        - ttf-dejavu
        - wqy-zenhei

    - name: Browsers
      pacman: name={{item}}
      with_items:
        - chromium
        - firefox
        - opera
        - w3m

    - name: Graphics
      pacman: name={{item}}
      with_items:
        - ghostscript
        - graphviz
        - imagemagick
        - perl-image-exiftool

    - name: Network monitoring
      pacman: name={{item}}
      with_items:
        - tcpdump
        - wireshark-gtk

    - name: Programmer tools
      pacman: name={{item}}
      with_items:
        - ack
        - dtach
        - screen
        - tmux

    - name: X11 utilities
      pacman: name={{item}}
      with_items:
        - lxpanel
        - parcellite
        - xclip
        - xorg-xbacklight
        - xorg-xdpyinfo
        - xorg-xev
        - xorg-xwininfo
        - xosd

- name: Install Feh (image viewer)
  hosts: arch
  tasks:
    - name: Feh (image viewer) prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - imlib2
        - giblib

    - name: Feh (image viewer) source
      git: repo=gh:benizi/feh
        dest=git/feh
      notify: install feh

  handlers:
    - name: install feh
      shell: make && make install
        chdir=git/feh
      notify: install feh

- name: Remote access tools
  hosts: laptops
  vars:
    tag: v-enable-scroll-lock
    cache: .cache/synergy.tar.gz

  tasks:
    - name: VNC and RDP
      sudo: yes
      pacman: name={{item}}
      with_items:
        - freerdp
        - gtk-vnc
        - x11vnc

    - name: Custom synergy prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - qt4

    - name: Custom synergy source
      get_url: url=https://github.com/benizi/synergy/archive/{{tag}}.tar.gz
        dest={{cache}}
        sha256sum=bc0863b0352f536473cd860b86bfcd09b345ec9fa55b3510ae595796d0e770f8

    - name: Custom synergy install
      shell: rm -r /tmp/synergy-{{tag}} &&
        tar zxf ~/{{cache}} &&
        cd synergy-{{tag}} &&
        with-python2 ./hm.sh conf -g1 &&
        with-python2 ./hm.sh build &&
        cp bin/synergy{c,d,s} ~/bin.local/
        chdir=/tmp
        creates=bin.local/synergyc

- name: Power settings
  hosts: laptops
  sudo: yes
  tasks:
    - name: Disable lid switch and suspend key
      lineinfile: dest=/etc/systemd/logind.conf
        regexp={{item.setting}}
        line='{{item.setting}}={{item.value}}'
      with_items:
        - { setting: HandleSuspendKey, value: ignore }
        - { setting: HandleLidSwitch, value: lock }
      notify: restart logind

    - name: Install utilities
      pacman: name={{item}}
      with_items:
        - pm-utils

  handlers:
    - name: restart logind
      service: name=systemd-logind state=restarted

- name: Prog langs
  hosts: laptops
  tasks:
    - name: Install prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - git
        - mercurial

    - name: Install Verman
      git: repo=bb:benizi/verman
        dest=git/verman

    # Verman uses ruby-build to install rubies
    - name: Fetch ruby-build
      git: repo=gh:sstephenson/ruby-build
        dest=git/ruby-build
      notify: Install ruby-build

    - meta: flush_handlers

    - name: Install langs
      shell: verman {{item.lang}} install {{item.version}} | with-python2 sh
        creates=/opt/{{item.lang}}/versions/{{item.version}}/bin/{{item.bin | default(item.lang)}}
      with_items:
        - { lang: erlang, version: '17.0', bin: erl }
        - { lang: elixir, version: v1.0.0 }
        - { lang: go, version: go1.3.3 }
        - { lang: node, version: v0.10.33 }
        - { lang: ruby, version: '1.9.3-p550' }
        - { lang: ruby, version: '2.0.0-p247' }
        - { lang: ruby, version: '2.1.1' }
        - { lang: ruby, version: '2.1.2' }

  handlers:
    - name: Install ruby-build
      command: ./install.sh
        chdir=git/ruby-build

- name: Password manager
  hosts: laptops
  tasks:
    - name: Install password-manager prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - gnome-keyring
        - libgnome-keyring

    - name: build password-manager
      command: make password-manager
        chdir=bin.local
        creates=password-manager

- name: Dev DNS
  hosts: laptops
  tasks:
    - name: Install local DNS prereqs
      sudo: yes
      pacman: name={{item}}
      with_items:
        - dhclient
        - dnsmasq

    - name: Ensure wicd uses dhclient
      sudo: yes
      lineinfile: dest=/etc/wicd/manager-settings.conf
        regexp='dhcp_client'
        line='dhcp_client = 1'
      notify: restart wicd

    - name: DHClient configuration
      sudo: yes
      copy: src=files/{{item}}
        dest=/etc/{{item}}
        owner=root
        group=root
        mode=0755
      with_items:
        - dhclient-enter-hooks
        - dhclient-exit-hooks

    - name: DNSMasq configuration dir
      sudo: yes
      file: dest=/etc/dnsmasq.d
        state=directory
        owner=root
        group=root
        mode=0770

    - name: DNSMasq configuration
      sudo: yes
      copy: src=files/dnsmasq.conf
        dest=/etc/dnsmasq.conf
        owner=root
        group=root
        mode=0644
      notify: restart dnsmasq

    - name: DNSMasq dev addresses
      sudo: yes
      copy: src=files/dev.conf
        dest=/etc/dnsmasq.d/dev.conf
        mode=0644
      notify: restart dnsmasq

    - name: Run DNSMasq
      sudo: true
      service: name=dnsmasq
        state=started
        enabled=yes

  handlers:
    - name: restart dnsmasq
      sudo: yes
      service: name=dnsmasq state=restarted

    - name: restart wicd
      sudo: yes
      service: name=wicd state=restarted
