---
- include: ansible.yml
- include: arch-repos.yml
- include: sudo-umask.yml
- include: inotify-limits.yml
- include: arch-sysctl.yml
- include: prereqs.yml
- include: ntp.yml
- include: initial-ssh.yml
- include: development.yml
- include: mercurial.yml
- include: xmonad.yml
- include: dotfiles.yml
- include: personal-dirs.yml
- include: dmenu.yml
- include: terminals.yml
- include: editors.yml
- include: nix.yml
- include: programming-languages.yml
- include: rebar.yml
- include: arch-build.yml
- include: docker.yml
- include: packages-system-tools.yml
- include: packages-hardware-info.yml
- include: packages-audio.yml
- include: packages-disks.yml
- include: packages-remote-filesystems.yml
- include: packages-compression.yml
- include: packages-fonts.yml
- include: packages-browsers.yml
- include: packages-shells.yml
- include: packages-terminals.yml
- include: packages-graphics.yml
- include: packages-multimedia.yml
- include: packages-messaging.yml
- include: packages-network-monitoring.yml
- include: packages-programmer-tools.yml
- include: packages-x11-utilities.yml
- include: packages-science.yml
- include: audio.yml
- include: radio.yml
- include: monitor.yml
- include: context.yml
- include: virtualization.yml
- include: avahi.yml
- include: vpn.yml
- include: user-groups.yml
- include: heroku.yml
- include: lxpanel.yml
- include: dropbox.yml
- include: mosh.yml
- include: pepperflash.yml
- include: user-services.yml
- include: feh.yml
- include: imv.yml
- include: remote-access.yml
- include: power.yml
- include: android.yml
- include: hub.yml
- include: aws.yml
- include: s3cmd.yml
- include: transproxy.yml
- include: password-manager.yml
- include: dev-dns.yml
- include: dev-servers.yml
- include: couchdb.yml
- include: aur.yml
- include: yubikey-neo.yml
- include: graphics-tablet.yml
- include: google-cloud-sdk.yml
