---
- include: ansible.yml
- include: arch-repos.yml
- include: sudo-umask.yml
- include: inotify-limits.yml
- include: arch-sysctl.yml
- include: prereqs.yml
- include: ntp.yml
- include: initial-ssh.yml
- include: development.yml
- include: mercurial.yml
- include: xmonad.yml
- include: dotfiles.yml
- include: personal-dirs.yml
- include: dmenu.yml
- include: terminals.yml
- include: editors.yml
- include: arch-build.yml
- include: packages.yml
- include: radio.yml
- include: monitor.yml
- include: context.yml
- include: virtualization.yml
- include: nix.yml
- include: avahi.yml
- include: vpn.yml
- include: user-groups.yml
- include: heroku.yml
- include: lxpanel.yml
- include: dropbox.yml
- include: mosh.yml
- include: pepperflash.yml
- include: user-services.yml
- include: feh.yml
- include: remote-access.yml
- include: power.yml
- include: programming-languages.yml
- include: rebar.yml
- include: android.yml
- include: aws.yml
- include: s3cmd.yml
- include: transproxy.yml
- include: password-manager.yml
- include: dev-dns.yml
- include: dev-servers.yml
- include: couchdb.yml
- include: aur.yml
- include: yubikey-neo.yml
- include: docker.yml
- include: graphics-tablet.yml
