- name: Acceptable terminal emulators
  hosts: laptops
  vars:
    rxvt_git: '{{gitbuild}}/rxvt-unicode'
    rxvt: /usr/local/bin/urxvt

  tasks:
    - name: Fallback (xterm and standard rxvt-unicode)
      sudo: true
      pacman: name={{item}}
      with_items:
        - rxvt-unicode
        - xterm

    - name: Acceptable terminal emulator detector (infocmp)
      sudo: true
      pacman: name=ncurses

    - name: Preferred (custom rxvt-unicode) prereqs
      sudo: true
      pacman: name={{item}}
      with_items:
        - libev

    - name: Preferred (custom rxvt-unicode) source
      git: repo='gh:benizi/rxvt-unicode'
        dest={{rxvt_git}}
        version=24bit-build
        remote=benizi

    - name: Preferred (custom rxvt-unicode) build
      shell: sh ./autogen.sh &&
        autoreconf &&
        ./configure --enable-24-bit-color --enable-xft --enable-perl --enable-256-color --disable-iso14755 &&
        make -j{{ansible_processor_vcpus}} &&
        make install
        chdir={{rxvt_git}}
        creates={{rxvt}}

    - name: Preferred (custom rxvt-unicode) link
      file: dest=~bhaskell/bin.local/term state=link src={{rxvt}}
