- name: Acceptable terminal emulators
  hosts: laptops
  vars:
    branch: 24bit-build
    extra_flags: '--enable-24-bit-color'
    force: false
    rxvt_git: '{{gitbuild}}/rxvt-unicode'
    rxvt: /usr/local/bin/urxvt

  tasks:
    - name: Fallback (xterm and standard rxvt-unicode)
      become: true
      pacman: name={{item}}
      with_items:
        - rxvt-unicode
        - xterm

    - name: Acceptable terminal emulator detector (infocmp)
      become: true
      pacman: name=ncurses

    - name: Preferred (custom rxvt-unicode) prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - libev

    - name: Preferred (custom rxvt-unicode) source
      git: repo='gh:benizi/rxvt-unicode'
        dest={{rxvt_git}}
        version={{branch}}
        remote=benizi
        force=yes

    - name: Check library dependencies (custom rxvt-unicode)
      command: 'ldd {{rxvt}}'
      register: checklibs
      changed_when: '" => not found" in checklibs.stdout or checklibs|failed'
      failed_when: false
      check_mode: no

    - name: Preferred (custom rxvt-unicode) build
      shell: |
        set -e
        cd {{rxvt_git}}
        sh ./autogen.sh
        autoreconf
        ./configure {{extra_flags}} --enable-xft --enable-perl --enable-256-color
        make clean
        make -j{{ansible_processor_vcpus}}
        make install
      args:
        creates: '{{omit if (force or checklibs|changed) else rxvt}}'

    - name: Preferred (custom rxvt-unicode) link
      file: dest={{homedir}}/bin.local/term state=link src={{rxvt}}
