- name: Acceptable terminal emulators
  hosts: laptops
  vars:
    branch: 24bit-build
    extra_flags: '--enable-24-bit-color'
    rxvt_git: '{{gitbuild}}/rxvt-unicode'
    rxvt: /usr/local/bin/urxvt

  tasks:
    - name: Fallback (xterm and standard rxvt-unicode)
      become: true
      pacman: name={{item}}
      with_items:
        - rxvt-unicode
        - xterm

    - name: Acceptable terminal emulator detector (infocmp)
      become: true
      pacman: name=ncurses

    - name: Preferred (custom rxvt-unicode) prereqs
      become: true
      pacman: name={{item}}
      with_items:
        - libev

    - name: Preferred (custom rxvt-unicode) source
      git: repo='gh:benizi/rxvt-unicode'
        dest={{rxvt_git}}
        version={{branch}}
        remote=benizi
        force=yes

    - name: Preferred (custom rxvt-unicode) build
      shell: sh ./autogen.sh &&
        autoreconf &&
        ./configure {{extra_flags}} --enable-xft --enable-perl --enable-256-color --disable-iso14755 &&
        make -j{{ansible_processor_vcpus}} &&
        make install
        chdir={{rxvt_git}}
        creates={{rxvt}}

    - name: Preferred (custom rxvt-unicode) link
      file: dest=~bhaskell/bin.local/term state=link src={{rxvt}}
