- name: Update Arch
  hosts: arch
  become: true
  tasks:
    - name: cache
      pacman: update_cache=yes
    - name: keys
      pacman: name=archlinux-keyring state=latest
    - name: upgrade
      pacman: upgrade=yes
