- name: User services
  hosts: arch
  vars:
    removed: [notification-daemon, xfce4-notifyd]
    services:
      - name: lxpanel
        description: LXPanel dock
        exec:
          start: [/bin/lxpanel]
      - name: parcellite
        description: Parcellite (clipboard manager)
        exec:
          start: [/bin/parcellite -d]
        extra:
          - StandardError=null
      - name: dropbox
        description: Dropbox daemon
        after: [lxpanel.service]
        exec:
          start: ['{{homedir}}/.dropbox-dist/dropboxd']
          reload: [/bin/kill -HUP $MAINPID]
      - name: nm-applet
        description: NetworkManager applet
        exec:
          start: [/bin/nm-applet]
      - name: mpd
        description: Music Player Daemon
        exec:
          start: [/bin/mpd --verbose --stderr --no-daemon]
    user_systemd: '{{homedir}}/.config/systemd/user'

  tasks:
    - name: User service dir
      file: dest={{user_systemd}} state=directory recurse=yes

    - name: Ensure old services are removed
      systemd:
        user: true
        name: '{{item}}'
        enabled: no
        state: stopped
        daemon_reload: yes
      with_items: '{{removed}}'
      # never fail, e.g., if the service isn't even installed
      failed_when: False

    - name: Services
      template:
        src: templates/user-service.service.j2
        dest: '{{user_systemd}}/{{item.name}}.service'
        mode: 0644
      with_items: '{{services}}'
      register: service_files
      notify:
        - reload user services
        - enable user services
        - start user services

  handlers:
    - name: reload user services
      command: systemctl --user daemon-reload

    - name: enable user services
      command: systemctl --user enable {{item.name}}.service
      with_items: '{{services}}'

    - name: start user services
      command: systemctl --user start {{item.name}}.service
      with_items: '{{services}}'
