- name: User services
  hosts: arch
  vars:
    services:
      - name: lxpanel
        description: LXPanel dock
        exec:
          start: [/bin/lxpanel]
      - name: parcellite
        description: Parcellite (clipboard manager)
        exec:
          start: [/bin/parcellite -d]
        extra:
          - StandardError=null
      - name: dropbox
        description: Dropbox daemon
        after: [lxpanel.service]
        exec:
          start: [/usr/bin/dropbox]
          reload: [/bin/kill -HUP $MAINPID]
    systemd: .config/systemd/user

  tasks:
    - name: User service dir
      file: dest=~bhaskell/{{systemd}} state=directory recurse=yes

    - name: Services
      template:
        src: templates/user-service.service.j2
        dest: '~bhaskell/{{systemd}}/{{item.name}}.service'
        mode: 0644
      with_items: '{{services}}'
      register: service_files
      notify:
        - reload user services
        - enable user services
        - start user services

  handlers:
    - name: reload user services
      command: systemctl --user daemon-reload

    - name: enable user services
      command: systemctl --user enable {{item.name}}.service
      with_items: '{{services}}'

    - name: start user services
      command: systemctl --user start {{item.name}}.service
      with_items: '{{services}}'
