- name: Fix user groups
  hosts: arch
  tasks:
    - name: Permissions
      become: true
      user:
        name: bhaskell
        append: yes
        groups:
          - audio
          - lp # for BlueZ D-Bus access
          - systemd-journal
          - uucp
          - wireshark
