- name: Virtualization
  hosts: arch
  become: true
  tasks:
    - name: Virtualization (packages)
      archpkg: name={{item}}
      with_items:
        - qemu
        - virt-manager
        - virtualbox
        - virtualbox-host-dkms
        - aur/virtualbox-ext-oracle

    - name: Virtualization (modules)
      copy: content='vboxdrv\nvboxnetadp\nvboxnetflt\nvboxpci\n'
        dest=/etc/modules-load.d/virtualbox.conf
        mode=0640

    - name: Virtualization (user groups)
      user: name=bhaskell
        append=yes
        groups=kvm,libvirt,vboxusers
