- name: Yubikey Neo support
  hosts: yubikey
  become: true
  tasks:
    - name: Yubikey manager and personalization
      pacman: name={{item}}
      with_items:
        - libu2f-host
        - python2-crypto
        - yubikey-manager-qt
        - yubikey-personalization-gui

    - name: CCID manager
      pacman:
        name: pcsclite
      register: ccid_manager

    - name: CCID manager service
      systemd:
        name: pcscd.socket
        state: '{{"restarted" if ccid_manager is changed else "started"}}'
        enabled: yes
        daemon_reload: '{{ccid_manager is changed}}'
