- name: Yubikey Neo support
  hosts: yubikey
  become: true
  tasks:
    - name: Install Yubikey manager
      aura: name=yubikey-neo-manager-git

    - name: CCID manager
      pacman: name=pcsclite

    - name: CCID manager service
      service: name=pcscd state=started enabled=yes
